apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: app
  namespace: karpenter
spec:
  template:
    metadata:
      labels:
        dedicated: app
    spec:
      requirements:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - "on-demand"  # on-demand | spot | reserved
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3.medium
      taints:
        - key: dedicated
          value: app
          effect: NoExecute
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # kubelet:
  #   maxPods: 110
  detailedMonitoring: true
  amiFamily: Bottlerocket  # AL2 | AL2023 | Bottlerocket
  role: "<KARPENTER_NODE_ROLE_NAME>"
  tags:
    Name: <NODE_NAMETAG>
    eks.amazonaws.com/nodegroup: <MNG_NAMETAG>
    owner: boseok
    project: wsi
  amiSelectorTerms:
    # - id: "<EC2_AMI>"
    - alias: "al2023@latest"  # al2 | al2023 | bottlerocket
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<CLUSTER_NAME>"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "<CLUSTER_NAME>"