[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y/%m/%d - %H:%M:%S
    Decode_Field_As escaped_utf8 log

[PARSER]
    Name   app
    Format regex
    Regex  ^(?<year>[^ ]*)-(?<month>[^ ]*)-(?<day>[^ ]*) (?<hour>[^ ]*):(?<minute>[^ ]*):(?<second>[^ ]*),[^ ]* [^ ]* [^ ]* (?<ip>[^ ]*) (?<port>[^ ]*) (?<method>[^ ]*) (?<path>[^ ]*) (?<statuscode>[^ ]*)