apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: nginx-prod
namePrefix: prod-

labels:
  - pairs:
      app.kubernetes.io/environment: prod
    includeSelectors: true

replicas:
  - name: nginx
    count: 3

images:
  - name: nginx
    newTag: latest

patches:
  - path: deployment.patch.yaml