configs:
  params:
    server.insecure: true
server:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-05d9b7b81a134b50c,subnet-0a1079083b07135ca
repoServer:
  initContainers:
    - name: helm-aws-s3
      image: alpine/helm:latest
      volumeMounts:
        - name: helm-working-dir
          mountPath: /helm-working-dir
      env:
        - name: HELM_CACHE_HOME
          value: /helm-working-dir
        - name: HELM_CONFIG_HOME
          value: /helm-working-dir
        - name: HELM_DATA_HOME
          value: /helm-working-dir
        - name: HELM_PLUGINS
          value: /helm-working-dir/plugins
      command: [ "/bin/sh", "-c" ]
      args:
        - apk --no-cache add curl;
          helm plugin install https://github.com/hypnoglow/helm-s3.git;
          rm -rf /helm-working-dir/plugins/https-github.com-hypnoglow-helm-s3.git;
          helm repo add product s3://skills-chart-bucket/product;
          chmod -R 777 $HELM_DATA_HOME;