system:
  certificateFilePath: "/greengrass/v2/device.pem.crt"
  privateKeyPath: "/greengrass/v2/private.pem.key"
  rootCaPath: "/greengrass/v2/AmazonRootCA1.pem"
  rootpath: "/greengrass/v2"
  thingName: "project-greengrass-core"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "2.18.0"
    configuration:
      awsRegion: "us-east-1"
      iotRoleAlias: "<ROLE_ALIAS_NAME>"
      iotDataEndpoint: "device-data-prefix-ats.iot.us-east-1q.amazonaws.com"
      iotCredEndpoint: "device-credentials-prefix.credentials.iot.us-east-1.amazonaws.com"