apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: <NS>
spec:
  podIdentity:
    provider: aws
    identityOwner: keda
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: aws-sqs-queue-scaledobject
  namespace: <NS>
spec:
  scaleTargetRef:
    name: <DEPLOYMENT_NAME>
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 2
  maxReplicaCount: 6
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: <SQS_QUEUE_URL>
      queueLength: "5"
      awsRegion: "ap-northeast-2"