apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: wsi
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      tolerations:
        - key: dedicated
          value: app
          effect: NoExecute
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: database
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: dedicated
                    operator: In
                    values:
                      - app
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - database
                topologyKey: topology.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - database
                topologyKey: kubernetes.io/hostname
              weight: 99
      restartPolicy: Always
      containers:
        - name: database
          image: postgres
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]
          resources:
            requests:
              cpu: "0.1"
              memory: 100Mi
            limits:
              memory: 200Mi
          livenessProbe:
            exec:
              command: ["pg_isready" ,"-U" ,"$(postgres)", "-d" ,"$(POSTGRE_DB)"]
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready" ,"-U" ,"$(postgres)", "-d" ,"$(POSTGRE_DB)"]
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          startupProbe:
            exec:
              command: ["pg_isready" ,"-U" ,"$(postgres)", "-d" ,"$(POSTGRE_DB)"]
            failureThreshold: 30
            timeoutSeconds: 5
            successThreshold: 1
            periodSeconds: 1
          env:
            - name: POSTGRES_DB
              value: test
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
              name: psql
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: wsi
spec:
  selector:
    app: database
  type: ClusterIP
  ports:
    - name: psql
      protocol: TCP
      port: 5432
      targetPort: psql
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: database
  namespace: wsi
spec:
  podSelector:
    matchLabels:
      app: database
  securityGroups:
    groupIds:
      - sg-017da76ba187fa6fa