apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: ws
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
spec:
  selector:
    app: product
  ports:
    - port: 8080
      targetPort: 8080