apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:  # resources에 추가적인 label을 부여
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false  # Selector에 해당 label을 추가하지 않음