apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1  # Secret region
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
# apiVersion: external-secrets.io/v1
# kind: SecretStore
# metadata:
#   name: secretsmanager
#   namespace: <NAMESPACE>
# spec:
#   provider:
#     aws:
#       service: SecretsManager
#       region: us-east-1  # Secret region
#       auth:
#         jwt:
#           serviceAccountRef:
#             name: external-secrets-sa  # IRSA name
# ---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: <NAMESPACE>
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore  # ClusterSecretStore | SecretStore
    name: secretsmanager
  target:
    name: db-secret  # K8s Secret Name
  data:
    - secretKey: MYSQL_PASSWORD  # K8s Secret Key
      remoteRef:
        key: wsi/db-secret  # AWS Secret Name
        property: password  # AWS Secret Key