apiVersion: dynamodb.services.k8s.aws/v1alpha1
kind: Table
metadata:
  name: <NAME>
  namespace: <NAMESPACE>
spec:
  tableName: <NAME>
  billingMode: PAY_PER_REQUEST
  tableClass: STANDARD
  attributeDefinitions:
    - attributeName: Id
      attributeType: S
    - attributeName: Service
      attributeType: S
  keySchema:
    - attributeName: Id
      keyType: HASH
    - attributeName: Service
      keyType: RANGE
  tags:
    - key: owner
    - value: boseok
    - key: project
    - value: wsi