[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /parser.conf

# parsing log with parser
[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       docker

# exclude log with /healthz path
[FILTER]
    Name   grep
    Match  *
    Exclude log /healthz